<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Migration\AbstractMultiPlatformMigration;
use Doctrine\DBAL\Schema\Schema;

final class Version20260923130000 extends AbstractMultiPlatformMigration
{
    public function getDescription(): string
    {
        return 'Add purchase orders so a parts-table selection can be saved, adjusted, and exported as DigiKey and Mouser basket files';
    }

    public function mySQLUp(Schema $schema): void
    {
        $this->addSql('CREATE TABLE purchase_orders (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE purchase_order_lines (id INT AUTO_INCREMENT NOT NULL, purchase_order_id INT NOT NULL, part_id INT NOT NULL, target_stock INT NOT NULL, quantity INT NOT NULL, INDEX IDX_PURCHASE_ORDER_LINES_ORDER (purchase_order_id), INDEX IDX_PURCHASE_ORDER_LINES_PART (part_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE purchase_order_lines ADD CONSTRAINT FK_PURCHASE_ORDER_LINES_ORDER FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE purchase_order_lines ADD CONSTRAINT FK_PURCHASE_ORDER_LINES_PART FOREIGN KEY (part_id) REFERENCES parts (id) ON DELETE CASCADE');
    }

    public function mySQLDown(Schema $schema): void
    {
        $this->addSql('ALTER TABLE purchase_order_lines DROP FOREIGN KEY FK_PURCHASE_ORDER_LINES_PART');
        $this->addSql('ALTER TABLE purchase_order_lines DROP FOREIGN KEY FK_PURCHASE_ORDER_LINES_ORDER');
        $this->addSql('DROP TABLE purchase_order_lines');
        $this->addSql('DROP TABLE purchase_orders');
    }

    public function sqLiteUp(Schema $schema): void
    {
        $this->addSql('CREATE TABLE purchase_orders (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL)');
        $this->addSql('CREATE TABLE purchase_order_lines (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, purchase_order_id INTEGER NOT NULL, part_id INTEGER NOT NULL, target_stock INTEGER NOT NULL, quantity INTEGER NOT NULL, CONSTRAINT FK_PURCHASE_ORDER_LINES_ORDER FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_PURCHASE_ORDER_LINES_PART FOREIGN KEY (part_id) REFERENCES parts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_PURCHASE_ORDER_LINES_ORDER ON purchase_order_lines (purchase_order_id)');
        $this->addSql('CREATE INDEX IDX_PURCHASE_ORDER_LINES_PART ON purchase_order_lines (part_id)');
    }

    public function sqLiteDown(Schema $schema): void
    {
        $this->addSql('DROP TABLE purchase_order_lines');
        $this->addSql('DROP TABLE purchase_orders');
    }

    public function postgreSQLUp(Schema $schema): void
    {
        $this->addSql('CREATE TABLE purchase_orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE purchase_order_lines (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, purchase_order_id INT NOT NULL, part_id INT NOT NULL, target_stock INT NOT NULL, quantity INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_PURCHASE_ORDER_LINES_ORDER ON purchase_order_lines (purchase_order_id)');
        $this->addSql('CREATE INDEX IDX_PURCHASE_ORDER_LINES_PART ON purchase_order_lines (part_id)');
        $this->addSql('ALTER TABLE purchase_order_lines ADD CONSTRAINT FK_PURCHASE_ORDER_LINES_ORDER FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE purchase_order_lines ADD CONSTRAINT FK_PURCHASE_ORDER_LINES_PART FOREIGN KEY (part_id) REFERENCES parts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function postgreSQLDown(Schema $schema): void
    {
        $this->addSql('DROP TABLE purchase_order_lines');
        $this->addSql('DROP TABLE purchase_orders');
    }
}
